---

name: Generate Manual

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gen_man:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: generate
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          ./man/gen-man
      - name: push updated manual
        run: |
          git config --global user.name denv-docs-bot
          git config --global user.email denv-docs-bot@users.noreply.github.com
          git add man
          git commit -m "Auto Man Page Update" || exit 0
          git push
