---
name: ShellCheck

on:
  push

permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/actions-shellcheck@v2
        with:
          ignore_paths: completions
          additional_files: 'denv _denv_entrypoint'
        env:
          SHELLCHECK_OPTS: -s sh -a -o all -Sstyle -Calways
